/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package televisionapplication;

import java.awt.Color;
import javax.swing.JOptionPane;

/**
 *
 * @author User
 */
public class SamsungTv extends javax.swing.JFrame {
    TelevisionApplication myTv = new TelevisionApplication();
    /**
     * Creates new form SamsungTv
     */
    public SamsungTv() {
        initComponents();
        tvPanel.setBackground(Color.gray);
        volumeBar.setVisible(false);
        channelBox.disable();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        tvPanel = new javax.swing.JPanel();
        channellabel = new javax.swing.JLabel();
        volumeBar = new javax.swing.JProgressBar();
        channel = new javax.swing.JLabel();
        tvLabel = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        powerButton = new javax.swing.JButton();
        channelUpButton = new javax.swing.JButton();
        channelDownButton = new javax.swing.JButton();
        volumeDownButton = new javax.swing.JButton();
        resetButton = new javax.swing.JButton();
        volumeUpButton = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        channelBox = new javax.swing.JTextField();
        ChangeChannelButton = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("SAMSUNG TELEVISION");

        tvPanel.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        volumeBar.setForeground(new java.awt.Color(255, 255, 0));

        javax.swing.GroupLayout tvPanelLayout = new javax.swing.GroupLayout(tvPanel);
        tvPanel.setLayout(tvPanelLayout);
        tvPanelLayout.setHorizontalGroup(
            tvPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(tvPanelLayout.createSequentialGroup()
                .addGroup(tvPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, tvPanelLayout.createSequentialGroup()
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(channel, javax.swing.GroupLayout.PREFERRED_SIZE, 54, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(channellabel, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(tvPanelLayout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(tvLabel)
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, tvPanelLayout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(volumeBar, javax.swing.GroupLayout.PREFERRED_SIZE, 206, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(129, 129, 129))
        );
        tvPanelLayout.setVerticalGroup(
            tvPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(tvPanelLayout.createSequentialGroup()
                .addGap(5, 5, 5)
                .addGroup(tvPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(channel, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(channellabel, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(tvLabel, javax.swing.GroupLayout.DEFAULT_SIZE, 301, Short.MAX_VALUE)
                .addGap(18, 18, 18)
                .addComponent(volumeBar, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        powerButton.setIcon(new javax.swing.ImageIcon(getClass().getResource("/televisionapplication/resources/power.png"))); // NOI18N
        powerButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                powerButtonActionPerformed(evt);
            }
        });

        channelUpButton.setIcon(new javax.swing.ImageIcon(getClass().getResource("/televisionapplication/resources/newUp.png"))); // NOI18N
        channelUpButton.setSelectedIcon(new javax.swing.ImageIcon(getClass().getResource("/televisionapplication/resources/newUp.png"))); // NOI18N
        channelUpButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                channelUpButtonActionPerformed(evt);
            }
        });

        channelDownButton.setIcon(new javax.swing.ImageIcon(getClass().getResource("/televisionapplication/resources/newDown.png"))); // NOI18N
        channelDownButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                channelDownButtonActionPerformed(evt);
            }
        });

        volumeDownButton.setIcon(new javax.swing.ImageIcon(getClass().getResource("/televisionapplication/resources/newDown.png"))); // NOI18N
        volumeDownButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                volumeDownButtonActionPerformed(evt);
            }
        });

        resetButton.setText("clear");
        resetButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                resetButtonActionPerformed(evt);
            }
        });

        volumeUpButton.setIcon(new javax.swing.ImageIcon(getClass().getResource("/televisionapplication/resources/newUp.png"))); // NOI18N
        volumeUpButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                volumeUpButtonActionPerformed(evt);
            }
        });

        jLabel1.setText("Channel");

        jLabel2.setText("Volume");

        ChangeChannelButton.setText("CH");
        ChangeChannelButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ChangeChannelButtonActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addComponent(powerButton, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(channelUpButton, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(channelDownButton, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(volumeUpButton, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel2)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(volumeDownButton, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(channelBox, javax.swing.GroupLayout.DEFAULT_SIZE, 35, Short.MAX_VALUE)
                .addGap(18, 18, 18)
                .addComponent(ChangeChannelButton, javax.swing.GroupLayout.PREFERRED_SIZE, 53, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(resetButton)
                .addContainerGap())
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(powerButton)
                    .addComponent(channelUpButton)
                    .addComponent(channelDownButton)
                    .addComponent(volumeUpButton)
                    .addComponent(volumeDownButton)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel1)
                            .addComponent(jLabel2)
                            .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                .addComponent(channelBox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(ChangeChannelButton)
                                .addComponent(resetButton)))))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(tvPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(tvPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(3, 3, 3))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void channelUpButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_channelUpButtonActionPerformed
        // TODO add your handling code here:
        if(myTv.getTvState()){
                myTv.channelUp();
                channellabel.setForeground(Color.WHITE);
                channel.setForeground(Color.WHITE);
                tvLabel.setIcon(new javax.swing.ImageIcon(getClass().getResource("/televisionapplication/resources/channel"+String.valueOf(myTv.getChannelId()+1)+".jpg")));
                channel.setText(myTv.getChannel(myTv.getChannelId()));
                channellabel.setText(String.valueOf(myTv.getChannelId()));
        }else{
            JOptionPane.showMessageDialog(null, "Tv is Off please Switch on");
        }
    }//GEN-LAST:event_channelUpButtonActionPerformed

    private void powerButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_powerButtonActionPerformed
        // TODO add your handling code here:
        if(myTv.getTvState()){
            myTv.turnTvOff();
            channelBox.disable();
            tvLabel.setIcon(null);
            tvPanel.setBackground(Color.gray);
            channellabel.setForeground(Color.gray);
            channel.setForeground(Color.gray);
        }else{
            myTv.turnTvOn();
            channelBox.enable();
            tvPanel.setBackground(Color.black);
            tvLabel.setIcon(new javax.swing.ImageIcon(getClass().getResource("/televisionapplication/resources/channel"+String.valueOf(myTv.getChannelId()+1)+".jpg")));
            channellabel.setForeground(Color.WHITE);
            channel.setForeground(Color.WHITE);
            channel.setText(myTv.getChannel(myTv.getChannelId()));
            channellabel.setText(String.valueOf(myTv.getChannelId()));
        }
    }//GEN-LAST:event_powerButtonActionPerformed

    private void channelDownButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_channelDownButtonActionPerformed
        // TODO add your handling code here:
        if(myTv.getTvState()){
                myTv.channelDown();
                channellabel.setForeground(Color.WHITE);
                channel.setForeground(Color.WHITE);
                tvLabel.setIcon(new javax.swing.ImageIcon(getClass().getResource("/televisionapplication/resources/channel"+String.valueOf(myTv.getChannelId()+1)+".jpg")));
                channel.setText(myTv.getChannel(myTv.getChannelId()));
                channellabel.setText(String.valueOf(myTv.getChannelId()));
        }else{
            JOptionPane.showMessageDialog(null, "Tv is Off please Switch on");
        }
       
    }//GEN-LAST:event_channelDownButtonActionPerformed

    private void volumeUpButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_volumeUpButtonActionPerformed
        // TODO add your handling code here:
        if(myTv.getTvState()){
                myTv.volumeUp();
                volumeBar.setVisible(true);
                volumeBar.setValue(myTv.getVolume());
                //volumeBar.setText(String.valueOf(myTv.getVolume()));
        }else{
            JOptionPane.showMessageDialog(null, "Tv is Off please Switch on");
        }
        
    }//GEN-LAST:event_volumeUpButtonActionPerformed

    private void volumeDownButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_volumeDownButtonActionPerformed
        // TODO add your handling code here:
         if(myTv.getTvState()){
                myTv.volumeDown();
                volumeBar.setVisible(true);
                volumeBar.setValue(myTv.getVolume());
                //volumeBar.setText(String.valueOf(myTv.getVolume()));
        }else{
            JOptionPane.showMessageDialog(null, "Tv is Off please Switch on");
        }
    }//GEN-LAST:event_volumeDownButtonActionPerformed

    private void resetButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_resetButtonActionPerformed
        // TODO add your handling code here:
        if(myTv.isTvSwitchedOn()){
            channellabel.setForeground(Color.black);
            channel.setForeground(Color.black);
            volumeBar.setVisible(false);
        }
    }//GEN-LAST:event_resetButtonActionPerformed

    private void ChangeChannelButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ChangeChannelButtonActionPerformed
        // TODO add your handling code here:
         if(myTv.getTvState()){
                int channelId = Integer.parseInt(channelBox.getText());
                myTv.changeChannel(channelId);
                channellabel.setForeground(Color.WHITE);
                channel.setForeground(Color.WHITE);
                tvLabel.setIcon(new javax.swing.ImageIcon(getClass().getResource("/televisionapplication/resources/channel"+String.valueOf(myTv.getChannelId()+1)+".jpg")));
                channel.setText(myTv.getChannel(myTv.getChannelId()));
                channellabel.setText(String.valueOf(myTv.getChannelId()));
        }else{
            JOptionPane.showMessageDialog(null, "Tv is Off please Switch on");
        }
    }//GEN-LAST:event_ChangeChannelButtonActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Windows".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(SamsungTv.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(SamsungTv.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(SamsungTv.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(SamsungTv.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                SamsungTv tvApp = new SamsungTv();
                tvApp.setLocationRelativeTo(null);
                tvApp.setIconImage(new javax.swing.ImageIcon(getClass().getResource("/televisionapplication/resources/icon.png")).getImage());
                tvApp.setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton ChangeChannelButton;
    private javax.swing.JLabel channel;
    private javax.swing.JTextField channelBox;
    private javax.swing.JButton channelDownButton;
    private javax.swing.JButton channelUpButton;
    private javax.swing.JLabel channellabel;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JButton powerButton;
    private javax.swing.JButton resetButton;
    private javax.swing.JLabel tvLabel;
    private javax.swing.JPanel tvPanel;
    private javax.swing.JProgressBar volumeBar;
    private javax.swing.JButton volumeDownButton;
    private javax.swing.JButton volumeUpButton;
    // End of variables declaration//GEN-END:variables
}
